name: C++ CI in ubuntu & win

on: 
  push:
    branches:
      - '*' 
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ubuntu-mingw:
    runs-on: ubuntu-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: configure
      env: 
        cc: gcc
        cxx: g++
      run: mkdir ./build && cd ./build && cmake ..
    - name: build with gcc
      run: cd ./build && make MiraiCPPlugin
  windows-msvc-single:
    runs-on: windows-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: configure
      run: mkdir ./build && cd ./build && cmake ..
    - name: build with msvc
      run:  cmake --build build --config Debug --target MiraiCPPlugin
  windows-mingw:
    runs-on: windows-latest
    steps:
    - name: checkout  
      uses: actions/checkout@v2
    - name: configure
      env: 
        cc: gcc
        cxx: g++
      run: mkdir ./build && cd ./build && cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - MinGW Makefiles" ..
    - name: build with gcc
      run: cmake --build build --config Debug --target MiraiCPPlugin
